### ISSUE TITLE
Memory Leak upon close of program

### ISSUE THREAD

**Issue by eclipse8129** [stuartmackenzie/falco-queue-buster#5]
Had three instances running during the AMD drop on 11/18.  Program remained open in background processes after closing.  Note, the queue was not stopped but would assume should stop upon closing the program.

V 1.0.10
Windows 7 64bit

![queue](https://user-images.githubusercontent.com/93722749/142494695-302b6a10-ffe1-4ab7-8540-681db0ed4776.jpg)

**Comment by stuartmackenzie** [comment]
We have resolved this issue by forcing the background process to close on app close.
